export * from './apps.service';
import { AppsService } from './apps.service';
export * from './apps.serviceInterface';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './blockchain.service';
import { BlockchainService } from './blockchain.service';
export * from './blockchain.serviceInterface';
export * from './config.service';
import { ConfigService } from './config.service';
export * from './config.serviceInterface';
export * from './cryptography.service';
import { CryptographyService } from './cryptography.service';
export * from './cryptography.serviceInterface';
export * from './info.service';
import { InfoService } from './info.service';
export * from './info.serviceInterface';
export * from './inputOutput.service';
import { InputOutputService } from './inputOutput.service';
export * from './inputOutput.serviceInterface';
export * from './process.service';
import { ProcessService } from './process.service';
export * from './process.serviceInterface';
export * from './system.service';
import { SystemService } from './system.service';
export * from './system.serviceInterface';
export const APIS = [AppsService, AuthService, BlockchainService, ConfigService, CryptographyService, InfoService, InputOutputService, ProcessService, SystemService];
