/**
 * Lethean Server
 * Lethean dAppServer
 *
 * The version of the OpenAPI document: 3.1.1
 * Contact: hello@lt.hn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { serverSDKConfiguration }                                     from '../configuration';



export interface AppsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: serverSDKConfiguration;

    /**
     * 
     * 
     */
    getMarketPlaceApps(extraHttpRequestParams?: any): Observable<string>;

    /**
     * 
     * 
     */
    installApp(extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     */
    listApps(extraHttpRequestParams?: any): Observable<string>;

    /**
     * 
     * 
     */
    removeApp(extraHttpRequestParams?: any): Observable<object>;

}
