/**
 * Lethean Server
 * Lethean dAppServer
 *
 * The version of the OpenAPI document: 3.1.1
 * Contact: hello@lt.hn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateAccountDTO } from '../model/models';
import { CreateAccountResponseDTO } from '../model/models';
import { DeleteAccountDTO } from '../model/models';
import { EncryptedRequestDTO } from '../model/models';
import { EncryptedResponseDTO } from '../model/models';


import { serverSDKConfiguration }                                     from '../configuration';



export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: serverSDKConfiguration;

    /**
     * 
     * 
     * @param deleteAccountDTO 
     */
    _delete(deleteAccountDTO: DeleteAccountDTO, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param createAccountDTO 
     */
    create(createAccountDTO: CreateAccountDTO, extraHttpRequestParams?: any): Observable<CreateAccountResponseDTO>;

    /**
     * 
     * 
     * @param encryptedRequestDTO 
     */
    login(encryptedRequestDTO: EncryptedRequestDTO, extraHttpRequestParams?: any): Observable<EncryptedResponseDTO>;

}
