/**
 * Lethean Server
 * Lethean dAppServer
 *
 * The version of the OpenAPI document: 3.1.1
 * Contact: hello@lt.hn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BlockchainLetheanDaemonStartDTO } from '../model/models';
import { BlockchainLetheanRPCDTO } from '../model/models';
import { BlockchainLetheanWalletStartDTO } from '../model/models';


import { serverSDKConfiguration }                                     from '../configuration';



export interface BlockchainServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: serverSDKConfiguration;

    /**
     * 
     * 
     * @param body 
     */
    exportBlockchain(body: any, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param body 
     */
    importBlockchain(body: any, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param blockchainLetheanRPCDTO 
     */
    jsonRpc(blockchainLetheanRPCDTO: BlockchainLetheanRPCDTO, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param blockchainLetheanDaemonStartDTO 
     */
    startDaemon(blockchainLetheanDaemonStartDTO: BlockchainLetheanDaemonStartDTO, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param blockchainLetheanWalletStartDTO 
     */
    startWallet(blockchainLetheanWalletStartDTO: BlockchainLetheanWalletStartDTO, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param body 
     */
    walletJsonRpc(body: any, extraHttpRequestParams?: any): Observable<{}>;

}
