/**
 * Lethean Server
 * Lethean dAppServer
 *
 * The version of the OpenAPI document: 3.1.1
 * Contact: hello@lt.hn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateFileDTO } from '../model/models';
import { FileDownloadRequest } from '../model/models';
import { FilePathCheckDTO } from '../model/models';
import { FilePathDTO } from '../model/models';


import { serverSDKConfiguration }                                     from '../configuration';



export interface InputOutputServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: serverSDKConfiguration;

    /**
     * 
     * 
     * @param fileDownloadRequest 
     */
    fetchFile(fileDownloadRequest: FileDownloadRequest, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param filePathDTO 
     */
    getDetailedDirectoryList(filePathDTO: FilePathDTO, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param filePathDTO 
     */
    getDirectoryList(filePathDTO: FilePathDTO, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param filePathDTO 
     */
    isDir(filePathDTO: FilePathDTO, extraHttpRequestParams?: any): Observable<FilePathCheckDTO>;

    /**
     * 
     * 
     * @param filePathDTO 
     */
    isFile(filePathDTO: FilePathDTO, extraHttpRequestParams?: any): Observable<FilePathCheckDTO>;

    /**
     * 
     * 
     * @param filePathDTO 
     */
    readFile(filePathDTO: FilePathDTO, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param createFileDTO 
     */
    writeFile(createFileDTO: CreateFileDTO, extraHttpRequestParams?: any): Observable<{}>;

}
