site_name: Lethean Documentation
copyright: Copyright &copy; 2017 - 2022 LetheanVPN
repo_url: https://github.com/letheanVPN/documentation
repo_name: letheanVPN/documentation
edit_uri: edit/main/docs/
docs_dir: files
site_url: https://docs.lt.hn
theme:
  name: material
  font: false
  language: en
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/git-alt
    code: octicons/alert-24
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: light-blue
      accent: blue
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue-grey
      accent: blue
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - announce.dismiss
    - toc.integrate
    - content.tabs.link

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/letheanVPN
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/lthn
    - icon: fontawesome/brands/github
      link: https://github.com/letheanVPN
extra_css:
  - stylesheets/extra.css
plugins:
  - social
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      enable_creation_date: true
  - search:
      lang:
        - en
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - tables
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.tabbed:
      alternate_style: true
