
name: lethean-server

on: [push,pull_request]

jobs:

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.21.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install
      - run: make build-windows
      - uses: papeloto/action-zip@v1
        with:
          files: build/lthn.exe
          recursive: false
          dest: windows.zip
      - uses: actions/upload-artifact@v3
        with:
          name: windows
          path: windows.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            windows.zip
  macos-arm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Select Xcode 12.0.0"
        uses: devbotsxyz/xcode-select@v1
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.20.1
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install
      - run: make build-macos-arm
      - run: chmod +x build/lthn && mv build/lthn lthn
      - run: tar -cvf macos-arm.tar lthn
      - uses: actions/upload-artifact@v3
        with:
          name: macos-arm
          path: macos-arm.tar
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            macos-arm.tar
  macos-intel:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Select Xcode 12.0.0"
        uses: devbotsxyz/xcode-select@v1
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.20.1
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install
      - run: make build-macos
      - run: chmod +x build/lthn && mv build/lthn lthn
      - run: tar -cvf macos-intel.tar lthn
      - uses: actions/upload-artifact@v3
        with:
          name: macos-intel
          path: macos-intel.tar
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            macos-intel.tar
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.20.1
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install
      - run: sudo apt-get update && sudo apt-get -y install libwebkit2gtk-4.0-37
      - run: make build-linux
      - run: chmod +x build/lthn && mv build/lthn lthn && tar -cvf linux.tar lthn
      - uses: actions/upload-artifact@v3
        with:
          name: linux
          path: linux.tar
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            linux.tar
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.20.1
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install
      - run: sudo apt-get update && sudo apt-get -y install libwebkit2gtk-4.0-37
      - run: deno bundle mod.ts server.bundle.js
      - uses: actions/upload-artifact@v3
        with:
          name: server.bundle.js
          path: server.bundle.js
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: server.bundle.js
#  launchers:
#    name: "Trigger: letheanVPN/launchers"
#    runs-on: ubuntu-latest
#    needs:
#      - windows
#      - linux
#      - macos-arm
#      - macos-intel
#    steps:
#      - name: Repository Dispatch
#        if: startsWith(github.ref, 'refs/tags/')
#        uses: peter-evans/repository-dispatch@v2
#        with:
#          token: ${{ secrets.REPO_ACCESS_TOKEN }}
#          event-type: build
#          repository: letheanVPN/launchers
