
name: Build and Release

on: 
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  compile-and-release:
    runs-on: ${{ matrix.build.os }}
    strategy:
      matrix: 
        build:
        - os: ubuntu-22.04
          compile: compile-lin
          artifact_name: lthn
          asset_name: lethean-server-linux-amd64

        - os: macos-12
          compile: compile-mac
          artifact_name: lthn
          asset_name: lethean-server-macos-amd64

        - os: macos-12
          compile: compile-mac-m1
          artifact_name: lthn
          asset_name: lethean-server-macos-aarch64

        - os: windows-2022
          compile: compile-win
          artifact_name: lthn.exe
          asset_name: lethean-server-win-amd64
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x 

      - run: deno task ${{ matrix.build.compile }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build.os }}-${{ matrix.build.compile }}
          if-no-files-found: error
          path: |
            ${{ github.workspace }}/build/lthn*

      - name: Upload binaries to release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/build/${{ matrix.build.artifact_name }}
          asset_name: ${{ matrix.build.asset_name }}
          tag: ${{ github.ref }}
  build-openapi:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x 

      - run: deno task build-openapi

      - uses: actions/upload-artifact@v4
        with:
          name: openapi.json
          if-no-files-found: error
          path: |
            ${{ github.workspace }}/openapi.json

      - name: Upload binaries to release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/openapi.json
          asset_name: openapi.json
          tag: ${{ github.ref }}