
name: lethean-server

on:
  push:
    branches:
      - 'main'
      - 'v*'
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'
      - 'v*'
    paths-ignore:
      - '**.md'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [ linux, macos-intel, macos-arm, windows ]
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.20.x
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm run server:build:${{ matrix.type }}
      - if: matrix.type != 'windows'
        run: chmod +x lethean-server && tar -cvf ${{ matrix.type }}.tar lethean-server
      - uses: papeloto/action-zip@v1
        if: matrix.type == 'windows'
        with:
          files: lethean-server.exe
          dest: ${{ matrix.type }}.zip
      - uses: actions/upload-artifact@v2
        if: matrix.type == 'windows'
        with:
          name: ${{ matrix.type }}
          path: ${{ matrix.type }}.zip
      - uses: actions/upload-artifact@v2
        if: matrix.type != 'windows'
        with:
          name: ${{ matrix.type }}
          path: ${{ matrix.type }}.tar
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ matrix.type }}.tar
            ${{ matrix.type }}.zip
