
name: Build and Release

on: 
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  compile-and-release:
    runs-on: ${{ matrix.build.os }}
    strategy:
      matrix: 
        build:
        - os: ubuntu-22.04
          compile: compile-lin
          artifact_name: lthn
          asset_name: lethean-server-linux-amd64

        - os: macos-12
          compile: compile-mac
          artifact_name: lthn
          asset_name: lethean-server-macos-amd64

        - os: macos-12
          compile: compile-mac-m1
          artifact_name: lthn
          asset_name: lethean-server-macos-aarch64

        - os: windows-2022
          compile: compile-win
          artifact_name: lthn.exe
          asset_name: lethean-server-win-amd64
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x 

      - run: deno task ${{ matrix.build.compile }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build.os }}-${{ matrix.build.compile }}
          if-no-files-found: error
          path: |
            ${{ github.workspace }}/build/lthn*

      - name: Upload binaries to release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/build/${{ matrix.build.artifact_name }}
          asset_name: ${{ matrix.build.asset_name }}
          tag: ${{ github.ref }}
  build-openapi:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x 

      - run: deno task build-openapi
      
      - name: Generate API Reference
        shell: bash
        run: |
          mkdir -p public
          echo '<!doctype html><html><head><title>API Reference</title><meta charset="utf-8" />'' > public/index.html"
          echo '<meta name="viewport"content="width=device-width, initial-scale=1"/>' >> public/index.html
          echo '<style>body{margin:0;}</style></head><body><script id="api-reference"type="application/json">' >> public/index.html
          cat openapi.json >> public/index.html
          echo '</script><script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script></body></html>' >> public/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - uses: actions/upload-artifact@v4
        with:
          name: openapi.json
          if-no-files-found: error
          path: |
            ${{ github.workspace }}/openapi.json

      - name: Upload binaries to release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/openapi.json
          asset_name: openapi.json
          tag: ${{ github.ref }}