
name: Build

on: [pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-22.04, macos-12, windows-2022]
        compile: [compile-lin, compile-mac, compile-mac-m1, compile-win]      
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x 
      - run: deno task ${{ matrix.compile }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.compile }}
          if-no-files-found: error
          path: |
            ${{ github.workspace }}/build/lthn*